NodeVersion="12.19.0"
compressedNodeModulesFile="node_modules.tar.gz"
OperationId="|nshQ2u3GWoc=.41c31e35_"
SourceDirectoryInBuildContainer="/tmp/8d914a2e4a16c83"
PlatformName="nodejs"
CompressDestinationDir="false"
